import { Recipe } from '../types';

export const DUMMY_RECIPES: Recipe[] = [
  {
    id: '1',
    title: 'Spicy Peanut Chicken Stir-fry',
    description: 'A vibrant and quick stir-fry featuring tender chicken, crisp vegetables, and a bold peanut-chili sauce.',
    meatType: 'Chicken',
    spiciness: 'Hot',
    prepTime: '30 minutes',
    difficulty: 'Easy',
    ingredients: ['500g chicken breast, sliced', '2 tbsp peanut butter', '1 tbsp sriracha', '2 tbsp soy sauce', '1 tbsp sesame oil', '1 red bell pepper', '1 cup broccoli florets', '3 cloves garlic', '1 tsp ginger'],
    instructions: '1. Mix peanut butter, sriracha, soy sauce, and sesame oil into a sauce.\n2. Stir-fry garlic and ginger in a hot wok for 30 seconds.\n3. Add chicken and cook until golden, about 5 minutes.\n4. Add vegetables and stir-fry 3 minutes.\n5. Pour sauce over and toss to coat. Serve over rice.',
    tags: ['stir-fry', 'peanut', 'quick', 'asian'],
  },
  {
    id: '2',
    title: 'Creamy Coconut Lentil Curry',
    description: 'A comforting and aromatic vegetarian curry slow-simmered with red lentils and coconut milk.',
    meatType: 'Vegetarian',
    spiciness: 'Medium',
    prepTime: '45 minutes',
    difficulty: 'Easy',
    ingredients: ['1 cup red lentils', '1 can coconut milk', '1 can diced tomatoes', '1 onion', '3 cloves garlic', '1 tbsp curry powder', '1 tsp cumin', '1 tsp turmeric', 'salt and pepper'],
    instructions: '1. Sauté onion and garlic until soft.\n2. Add curry powder, cumin, turmeric and toast 1 minute.\n3. Add lentils, tomatoes, and coconut milk.\n4. Simmer 25 minutes until lentils are tender.\n5. Season and serve with naan.',
    tags: ['curry', 'vegetarian', 'lentils', 'coconut'],
  },
  {
    id: '3',
    title: 'Korean BBQ Beef Bulgogi',
    description: 'Thinly sliced beef marinated in a sweet and savory soy-garlic sauce, grilled to perfection.',
    meatType: 'Beef',
    spiciness: 'Mild',
    prepTime: '45 minutes (plus marinating time)',
    difficulty: 'Intermediate',
    ingredients: ['600g ribeye, thinly sliced', '4 tbsp soy sauce', '2 tbsp sugar', '1 tbsp sesame oil', '5 cloves garlic, minced', '1 pear, grated', '2 green onions', '1 tbsp sesame seeds'],
    instructions: '1. Combine soy sauce, sugar, sesame oil, garlic, and grated pear.\n2. Marinate beef for at least 2 hours.\n3. Grill or pan-fry over high heat 2–3 minutes per side.\n4. Garnish with green onions and sesame seeds.',
    tags: ['korean', 'bbq', 'beef', 'grilled'],
  },
  {
    id: '4',
    title: 'Smoky Chipotle Pork Tacos',
    description: 'Tender slow-cooked pork shoulder shredded and tossed in a rich, smoky chipotle sauce.',
    meatType: 'Pork',
    spiciness: 'Hot',
    prepTime: '3 hours 30 minutes',
    difficulty: 'Intermediate',
    ingredients: ['1kg pork shoulder', '2 chipotle peppers in adobo', '1 tsp smoked paprika', '1 tsp cumin', '4 cloves garlic', '1 orange, juiced', 'corn tortillas', 'cilantro, onion, lime to serve'],
    instructions: '1. Blend chipotles, paprika, cumin, garlic, and orange juice.\n2. Rub over pork and slow cook at 150°C for 3 hours.\n3. Shred pork with forks and toss in cooking juices.\n4. Serve in warm tortillas with cilantro, onion, and lime.',
    tags: ['tacos', 'pork', 'chipotle', 'slow-cook'],
  },
  {
    id: '5',
    title: 'Zesty Shrimp Scampi Pasta',
    description: 'Succulent shrimp sautéed with abundant garlic, lemon, and white wine over linguine.',
    meatType: 'Seafood',
    spiciness: 'Mild',
    prepTime: '25 minutes',
    difficulty: 'Easy',
    ingredients: ['400g linguine', '500g large shrimp, peeled', '6 cloves garlic', '1/2 cup white wine', '3 tbsp butter', '2 tbsp olive oil', '1 lemon', 'parsley', 'chili flakes'],
    instructions: '1. Cook pasta until al dente.\n2. Sauté garlic in butter and oil until fragrant.\n3. Add shrimp and cook 2 minutes per side.\n4. Deglaze with white wine, add lemon juice.\n5. Toss with pasta and parsley.',
    tags: ['pasta', 'seafood', 'shrimp', 'quick'],
  },
  {
    id: '6',
    title: 'Mediterranean Lemon Garlic Chicken',
    description: 'Juicy chicken thighs marinated in a zesty lemon-garlic-oregano sauce, roasted until golden.',
    meatType: 'Chicken',
    spiciness: 'Mild',
    prepTime: '50 minutes (plus marinating time)',
    difficulty: 'Easy',
    ingredients: ['8 chicken thighs', '4 cloves garlic', '2 lemons, juiced and zested', '2 tbsp olive oil', '1 tbsp dried oregano', '1 tsp paprika', 'salt and pepper', 'fresh parsley'],
    instructions: '1. Mix garlic, lemon, olive oil, oregano, and paprika.\n2. Marinate chicken at least 1 hour.\n3. Roast at 200°C for 35–40 minutes until golden.\n4. Rest 5 minutes and serve with fresh parsley.',
    tags: ['mediterranean', 'chicken', 'roasted', 'lemon'],
  },
  {
    id: '7',
    title: 'Black Bean and Corn Veggie Burgers',
    description: 'Hearty and flavorful homemade veggie burgers packed with black beans, corn, and spices.',
    meatType: 'Vegetarian',
    spiciness: 'Medium',
    prepTime: '40 minutes',
    difficulty: 'Intermediate',
    ingredients: ['2 cans black beans', '1 cup corn', '1/2 cup breadcrumbs', '1 egg', '1 tsp cumin', '1 tsp smoked paprika', '1/2 red onion', '2 cloves garlic', 'burger buns and toppings'],
    instructions: '1. Mash black beans, leaving some texture.\n2. Mix in corn, breadcrumbs, egg, and spices.\n3. Form into patties and refrigerate 20 minutes.\n4. Pan-fry 4 minutes per side until crispy.\n5. Serve on buns with your favourite toppings.',
    tags: ['burger', 'vegetarian', 'black-bean', 'plant-based'],
  },
  {
    id: '8',
    title: 'Hearty Beef and Mushroom Stew',
    description: 'A classic, soul-warming beef stew with tender chunks of beef, earthy mushrooms, and root vegetables.',
    meatType: 'Beef',
    spiciness: 'Mild',
    prepTime: '2 hours 30 minutes',
    difficulty: 'Intermediate',
    ingredients: ['800g beef chuck, cubed', '300g mushrooms', '2 carrots', '2 potatoes', '1 onion', '3 cloves garlic', '2 cups beef stock', '1 cup red wine', '2 tbsp tomato paste', 'fresh thyme'],
    instructions: '1. Brown beef in batches and set aside.\n2. Sauté onion, garlic, and mushrooms.\n3. Add tomato paste, wine, and stock.\n4. Return beef and add vegetables and thyme.\n5. Simmer covered 2 hours until tender.',
    tags: ['stew', 'beef', 'comfort-food', 'slow-cook'],
  },
  {
    id: '9',
    title: 'Sweet and Sour Pork with Pineapple',
    description: 'Crispy fried pork pieces tossed in a classic tangy-sweet sauce with chunks of pineapple and peppers.',
    meatType: 'Pork',
    spiciness: 'Mild',
    prepTime: '40 minutes',
    difficulty: 'Intermediate',
    ingredients: ['500g pork loin, cubed', '1 cup pineapple chunks', '1 red pepper', '1 green pepper', '1/4 cup vinegar', '3 tbsp sugar', '2 tbsp ketchup', '1 tbsp soy sauce', 'cornstarch for coating'],
    instructions: '1. Coat pork in cornstarch and fry until golden.\n2. Mix vinegar, sugar, ketchup, and soy sauce.\n3. Stir-fry peppers 2 minutes.\n4. Add sauce and pineapple, bring to a simmer.\n5. Toss in crispy pork and serve immediately.',
    tags: ['chinese', 'pork', 'sweet-sour', 'pineapple'],
  },
  {
    id: '10',
    title: 'Mango Habanero Grilled Chicken Skewers',
    description: 'Juicy chicken pieces marinated in a vibrant, sweet, and intensely spicy mango-habanero glaze.',
    meatType: 'Chicken',
    spiciness: 'Extra Hot',
    prepTime: '45 minutes (plus marinating time)',
    difficulty: 'Intermediate',
    ingredients: ['600g chicken breast, cubed', '1 mango, pureed', '2 habanero peppers', '2 tbsp lime juice', '1 tbsp honey', '2 cloves garlic', '1 tsp cumin', 'wooden skewers'],
    instructions: '1. Blend mango, habaneros, lime, honey, garlic, and cumin.\n2. Marinate chicken 2+ hours.\n3. Thread onto skewers.\n4. Grill over high heat 10–12 minutes, turning and basting.\n5. Rest and serve with extra mango salsa.',
    tags: ['grilled', 'chicken', 'spicy', 'mango'],
  },
  {
    id: '11',
    title: 'Lemon Herb Baked Salmon',
    description: 'Flaky, tender salmon fillets baked with a fragrant herb crust and bright lemon.',
    meatType: 'Seafood',
    spiciness: 'Mild',
    prepTime: '25 minutes',
    difficulty: 'Easy',
    ingredients: ['4 salmon fillets', '2 lemons', '3 tbsp olive oil', '2 cloves garlic', '1 tbsp fresh dill', '1 tbsp fresh parsley', 'salt and pepper'],
    instructions: '1. Preheat oven to 200°C.\n2. Mix olive oil, garlic, dill, parsley, and lemon zest.\n3. Coat salmon with herb mixture.\n4. Bake 12–15 minutes until flaky.\n5. Serve with lemon wedges.',
    tags: ['salmon', 'baked', 'healthy', 'lemon'],
  },
  {
    id: '12',
    title: 'Fiery Szechuan Beef Noodles',
    description: 'An intensely flavorful and spicy noodle dish featuring tender beef strips, Szechuan peppercorns, and chili oil.',
    meatType: 'Beef',
    spiciness: 'Extra Hot',
    prepTime: '35 minutes',
    difficulty: 'Intermediate',
    ingredients: ['400g beef sirloin, strips', '200g egg noodles', '2 tbsp chili oil', '1 tbsp Szechuan peppercorns', '3 tbsp soy sauce', '1 tbsp rice vinegar', '4 cloves garlic', '1 tsp ginger', 'green onions'],
    instructions: '1. Cook noodles and set aside.\n2. Toast Szechuan peppercorns and grind.\n3. Sear beef strips in very hot wok.\n4. Add garlic, ginger, chili oil, and peppercorns.\n5. Toss with noodles, soy sauce, and vinegar. Top with green onions.',
    tags: ['szechuan', 'noodles', 'beef', 'spicy'],
  },
];
